// Additional questions batch 2 - History, Entertainment, Sports, Astronomy, General
export const batch2Questions = [
    // HISTORY - 60 questions
    { q: "Who was the first Roman Emperor?", o: ["Julius Caesar", "Augustus", "Nero", "Caligula"], a: "Augustus", c: "history", d: "medium", p: 15, t: 30 },
    { q: "In which year did World War I begin?", o: ["1912", "1914", "1916", "1918"], a: "1914", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was the first female Prime Minister of the UK?", o: ["Theresa May", "Margaret Thatcher", "Queen Elizabeth II", "Angela Merkel"], a: "Margaret Thatcher", c: "history", d: "medium", p: 15, t: 30 },
    { q: "The French Revolution began in which year?", o: ["1776", "1789", "1799", "1804"], a: "1789", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was the leader of the Soviet Union during World War II?", o: ["Lenin", "Stalin", "Khrushchev", "Gorbachev"], a: "Stalin", c: "history", d: "easy", p: 10, t: 20 },
    { q: "The Magna Carta was signed in which year?", o: ["1066", "1215", "1415", "1515"], a: "1215", c: "history", d: "hard", p: 20, t: 35 },
    { q: "Who discovered America for Spain in 1492?", o: ["Vasco da Gama", "Christopher Columbus", "Ferdinand Magellan", "Amerigo Vespucci"], a: "Christopher Columbus", c: "history", d: "easy", p: 10, t: 20 },
    { q: "The Renaissance began in which country?", o: ["France", "Spain", "Italy", "England"], a: "Italy", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was the first President of South Africa after apartheid?", o: ["Desmond Tutu", "F.W. de Klerk", "Nelson Mandela", "Thabo Mbeki"], a: "Nelson Mandela", c: "history", d: "easy", p: 10, t: 20 },
    { q: "The Cold War was primarily between which two superpowers?", o: ["USA and China", "USSR and UK", "USA and USSR", "China and USSR"], a: "USA and USSR", c: "history", d: "easy", p: 10, t: 20 },
    { q: "Who wrote the Communist Manifesto?", o: ["Lenin", "Stalin", "Karl Marx", "Mao Zedong"], a: "Karl Marx", c: "history", d: "medium", p: 15, t: 30 },
    { q: "The American Civil War ended in which year?", o: ["1861", "1863", "1865", "1867"], a: "1865", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was the Egyptian queen who had relationships with Julius Caesar and Mark Antony?", o: ["Nefertiti", "Cleopatra", "Hatshepsut", "Nefertari"], a: "Cleopatra", c: "history", d: "easy", p: 10, t: 20 },
    { q: "The Industrial Revolution began in which country?", o: ["France", "Germany", "England", "USA"], a: "England", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was the Mongol leader who created the largest land empire?", o: ["Kublai Khan", "Genghis Khan", "Tamerlane", "Attila the Hun"], a: "Genghis Khan", c: "history", d: "medium", p: 15, t: 30 },
    { q: "The Declaration of Independence was signed in which year?", o: ["1774", "1776", "1778", "1780"], a: "1776", c: "history", d: "easy", p: 10, t: 20 },
    { q: "Who was the first woman to fly solo across the Atlantic?", o: ["Bessie Coleman", "Amelia Earhart", "Harriet Quimby", "Jacqueline Cochran"], a: "Amelia Earhart", c: "history", d: "medium", p: 15, t: 30 },
    { q: "The Battle of Waterloo was fought in which year?", o: ["1805", "1815", "1825", "1835"], a: "1815", c: "history", d: "hard", p: 20, t: 35 },
    { q: "Who was the first man in space?", o: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], a: "Yuri Gagarin", c: "history", d: "medium", p: 15, t: 25 },
    { q: "The Spanish Armada was defeated in which year?", o: ["1488", "1588", "1688", "1788"], a: "1588", c: "history", d: "hard", p: 20, t: 35 },
    { q: "Who was the British Prime Minister during most of World War II?", o: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Anthony Eden"], a: "Winston Churchill", c: "history", d: "easy", p: 10, t: 20 },
    { q: "The Black Death pandemic occurred in which century?", o: ["12th", "13th", "14th", "15th"], a: "14th", c: "history", d: "medium", p: 15, t: 30 },
    { q: "Who was the first Emperor of China?", o: ["Qin Shi Huang", "Han Wudi", "Tang Taizong", "Kublai Khan"], a: "Qin Shi Huang", c: "history", d: "hard", p: 20, t: 35 },
    { q: "The Treaty of Versailles ended which war?", o: ["World War I", "World War II", "Franco-Prussian War", "Napoleonic Wars"], a: "World War I", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who led India to independence from British rule?", o: ["Jawaharlal Nehru", "Mahatma Gandhi", "Subhas Chandra Bose", "Sardar Patel"], a: "Mahatma Gandhi", c: "history", d: "easy", p: 10, t: 20 },
    { q: "The Hundred Years' War was between which two countries?", o: ["England and France", "Spain and Portugal", "Germany and France", "England and Spain"], a: "England and France", c: "history", d: "medium", p: 15, t: 30 },
    { q: "Who was assassinated in Sarajevo in 1914, triggering World War I?", o: ["Kaiser Wilhelm", "Archduke Franz Ferdinand", "Tsar Nicholas II", "King George V"], a: "Archduke Franz Ferdinand", c: "history", d: "hard", p: 20, t: 35 },
    { q: "The Suez Crisis occurred in which year?", o: ["1946", "1956", "1966", "1976"], a: "1956", c: "history", d: "hard", p: 20, t: 35 },
    { q: "Who was the first Holy Roman Emperor?", o: ["Julius Caesar", "Augustus", "Constantine", "Charlemagne"], a: "Charlemagne", c: "history", d: "hard", p: 20, t: 35 },
    { q: "The Cuban Missile Crisis occurred in which year?", o: ["1959", "1962", "1965", "1968"], a: "1962", c: "history", d: "medium", p: 15, t: 30 },
    { q: "Who painted the ceiling of the Sistine Chapel?", o: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Donatello"], a: "Michelangelo", c: "history", d: "medium", p: 15, t: 25 },
    { q: "The Ottoman Empire ended after which war?", o: ["World War I", "World War II", "Crimean War", "Balkan Wars"], a: "World War I", c: "history", d: "medium", p: 15, t: 30 },
    { q: "Who was the first female ruler of Russia?", o: ["Catherine the Great", "Elizabeth I", "Anna Ivanovna", "Catherine I"], a: "Catherine I", c: "history", d: "hard", p: 20, t: 35 },
    { q: "The Vietnam War ended in which year?", o: ["1973", "1975", "1977", "1979"], a: "1975", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who invented the printing press in Europe?", o: ["Johannes Gutenberg", "William Caxton", "Aldus Manutius", "Benjamin Franklin"], a: "Johannes Gutenberg", c: "history", d: "medium", p: 15, t: 30 },
    { q: "The Battle of Hastings was fought in which year?", o: ["1066", "1166", "1266", "1366"], a: "1066", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was the last Tsar of Russia?", o: ["Alexander III", "Nicholas I", "Nicholas II", "Peter the Great"], a: "Nicholas II", c: "history", d: "medium", p: 15, t: 30 },
    { q: "The Reformation was started by which religious figure?", o: ["John Calvin", "Martin Luther", "Henry VIII", "John Knox"], a: "Martin Luther", c: "history", d: "medium", p: 15, t: 30 },
    { q: "Pearl Harbor was attacked in which year?", o: ["1939", "1940", "1941", "1942"], a: "1941", c: "history", d: "easy", p: 10, t: 20 },
    { q: "Who was the first woman to win a Nobel Prize?", o: ["Mother Teresa", "Marie Curie", "Rosalind Franklin", "Dorothy Hodgkin"], a: "Marie Curie", c: "history", d: "medium", p: 15, t: 25 },
    { q: "The Byzantine Empire fell in which year?", o: ["1204", "1353", "1453", "1553"], a: "1453", c: "history", d: "hard", p: 20, t: 35 },
    { q: "Who led the Bolshevik Revolution in Russia?", o: ["Stalin", "Trotsky", "Lenin", "Kerensky"], a: "Lenin", c: "history", d: "medium", p: 15, t: 30 },
    { q: "The Great Fire of London occurred in which year?", o: ["1566", "1666", "1766", "1866"], a: "1666", c: "history", d: "hard", p: 20, t: 35 },
    { q: "Who was the first African American President of the USA?", o: ["Martin Luther King Jr.", "Barack Obama", "Jesse Jackson", "Colin Powell"], a: "Barack Obama", c: "history", d: "easy", p: 10, t: 15 },
    { q: "The Korean War began in which year?", o: ["1948", "1950", "1952", "1954"], a: "1950", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was known as the 'Iron Lady'?", o: ["Golda Meir", "Indira Gandhi", "Margaret Thatcher", "Angela Merkel"], a: "Margaret Thatcher", c: "history", d: "easy", p: 10, t: 20 },
    { q: "The Chernobyl disaster occurred in which year?", o: ["1984", "1986", "1988", "1990"], a: "1986", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was the first person to circumnavigate the globe?", o: ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "James Cook"], a: "Ferdinand Magellan", c: "history", d: "medium", p: 15, t: 30 },
    { q: "The Opium Wars were fought between China and which country?", o: ["France", "Britain", "USA", "Japan"], a: "Britain", c: "history", d: "medium", p: 15, t: 30 },
    { q: "Who was the founder of the Mongol Empire?", o: ["Kublai Khan", "Genghis Khan", "Tamerlane", "Batu Khan"], a: "Genghis Khan", c: "history", d: "medium", p: 15, t: 25 },
    { q: "The Space Race was primarily between which two countries?", o: ["USA and China", "USA and USSR", "USSR and UK", "USA and Japan"], a: "USA and USSR", c: "history", d: "easy", p: 10, t: 20 },
    { q: "Who wrote 'The Prince', a political treatise?", o: ["Thomas Hobbes", "John Locke", "Niccolò Machiavelli", "Jean-Jacques Rousseau"], a: "Niccolò Machiavelli", c: "history", d: "hard", p: 20, t: 35 },
    { q: "The Meiji Restoration occurred in which country?", o: ["China", "Korea", "Japan", "Thailand"], a: "Japan", c: "history", d: "hard", p: 20, t: 35 },
    { q: "Who was the first Chancellor of Germany?", o: ["Adolf Hitler", "Otto von Bismarck", "Konrad Adenauer", "Helmut Kohl"], a: "Otto von Bismarck", c: "history", d: "hard", p: 20, t: 35 },
    { q: "The Silk Road connected China with which region?", o: ["Africa", "Europe", "Americas", "Australia"], a: "Europe", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was the longest-reigning British monarch before Elizabeth II?", o: ["Queen Victoria", "George III", "Edward VII", "Henry VIII"], a: "Queen Victoria", c: "history", d: "medium", p: 15, t: 30 },
    { q: "The Aztec Empire was located in which modern-day country?", o: ["Peru", "Guatemala", "Mexico", "Colombia"], a: "Mexico", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was the first woman in space?", o: ["Sally Ride", "Valentina Tereshkova", "Svetlana Savitskaya", "Mae Jemison"], a: "Valentina Tereshkova", c: "history", d: "hard", p: 20, t: 35 },
    { q: "The Inca Empire was located primarily in which modern-day country?", o: ["Mexico", "Brazil", "Peru", "Chile"], a: "Peru", c: "history", d: "medium", p: 15, t: 25 },
    { q: "Who was the Roman general who crossed the Rubicon?", o: ["Augustus", "Julius Caesar", "Mark Antony", "Pompey"], a: "Julius Caesar", c: "history", d: "medium", p: 15, t: 30 },

    // ENTERTAINMENT - 60 questions
    { q: "Who directed 'The Godfather'?", o: ["Martin Scorsese", "Francis Ford Coppola", "Steven Spielberg", "Quentin Tarantino"], a: "Francis Ford Coppola", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Which band sang 'Bohemian Rhapsody'?", o: ["The Beatles", "Led Zeppelin", "Queen", "Pink Floyd"], a: "Queen", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Who played Iron Man in the Marvel Cinematic Universe?", o: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], a: "Robert Downey Jr.", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Which movie won the first Academy Award for Best Picture?", o: ["Wings", "The Jazz Singer", "Sunrise", "Metropolis"], a: "Wings", c: "entertainment", d: "hard", p: 20, t: 35 },
    { q: "Who wrote the novel '1984'?", o: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], a: "George Orwell", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Which TV show features the character Walter White?", o: ["The Sopranos", "Breaking Bad", "The Wire", "Mad Men"], a: "Breaking Bad", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Who composed the music for 'Star Wars'?", o: ["Hans Zimmer", "John Williams", "Ennio Morricone", "Howard Shore"], a: "John Williams", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Which Shakespeare play features the characters Romeo and Juliet?", o: ["Hamlet", "Macbeth", "Romeo and Juliet", "Othello"], a: "Romeo and Juliet", c: "entertainment", d: "easy", p: 10, t: 15 },
    { q: "Who painted 'The Starry Night'?", o: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"], a: "Vincent van Gogh", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Which movie features the quote 'May the Force be with you'?", o: ["Star Trek", "Star Wars", "Guardians of the Galaxy", "Interstellar"], a: "Star Wars", c: "entertainment", d: "easy", p: 10, t: 15 },
    { q: "Who wrote 'To Kill a Mockingbird'?", o: ["Harper Lee", "Mark Twain", "F. Scott Fitzgerald", "Ernest Hemingway"], a: "Harper Lee", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Which band is known as the 'Fab Four'?", o: ["The Rolling Stones", "The Beatles", "The Who", "Led Zeppelin"], a: "The Beatles", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Who directed 'Pulp Fiction'?", o: ["Martin Scorsese", "Quentin Tarantino", "Steven Spielberg", "Christopher Nolan"], a: "Quentin Tarantino", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Which novel begins with 'Call me Ishmael'?", o: ["Moby-Dick", "The Old Man and the Sea", "Treasure Island", "Robinson Crusoe"], a: "Moby-Dick", c: "entertainment", d: "hard", p: 20, t: 35 },
    { q: "Who played Jack in 'Titanic'?", o: ["Brad Pitt", "Leonardo DiCaprio", "Tom Cruise", "Johnny Depp"], a: "Leonardo DiCaprio", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Which musical features the song 'Defying Gravity'?", o: ["Wicked", "The Phantom of the Opera", "Les Misérables", "Hamilton"], a: "Wicked", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Who wrote 'Pride and Prejudice'?", o: ["Charlotte Brontë", "Emily Brontë", "Jane Austen", "Mary Shelley"], a: "Jane Austen", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Which movie won the Oscar for Best Picture in 2020?", o: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"], a: "Parasite", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Who sang 'Like a Rolling Stone'?", o: ["The Beatles", "Bob Dylan", "The Rolling Stones", "Bruce Springsteen"], a: "Bob Dylan", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Which TV series is set in the fictional land of Westeros?", o: ["The Witcher", "Game of Thrones", "The Lord of the Rings", "Vikings"], a: "Game of Thrones", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Who directed 'Schindler's List'?", o: ["Martin Scorsese", "Steven Spielberg", "Francis Ford Coppola", "Ridley Scott"], a: "Steven Spielberg", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Which artist painted 'The Last Supper'?", o: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], a: "Leonardo da Vinci", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Who wrote 'The Great Gatsby'?", o: ["Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner"], a: "F. Scott Fitzgerald", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Which movie features the character Forrest Gump?", o: ["The Green Mile", "Forrest Gump", "Cast Away", "Philadelphia"], a: "Forrest Gump", c: "entertainment", d: "easy", p: 10, t: 15 },
    { q: "Who composed 'The Four Seasons'?", o: ["Mozart", "Beethoven", "Vivaldi", "Bach"], a: "Vivaldi", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Which TV show features the Central Perk coffee shop?", o: ["Seinfeld", "Friends", "How I Met Your Mother", "The Big Bang Theory"], a: "Friends", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Who painted 'Guernica'?", o: ["Salvador Dalí", "Pablo Picasso", "Joan Miró", "Diego Rivera"], a: "Pablo Picasso", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Which movie trilogy is based on J.R.R. Tolkien's novels?", o: ["The Hobbit", "The Lord of the Rings", "The Chronicles of Narnia", "Harry Potter"], a: "The Lord of the Rings", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Who sang 'Purple Rain'?", o: ["Michael Jackson", "Prince", "David Bowie", "Stevie Wonder"], a: "Prince", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Which Shakespeare play features the line 'To be or not to be'?", o: ["Macbeth", "Hamlet", "King Lear", "Othello"], a: "Hamlet", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Who directed 'The Shawshank Redemption'?", o: ["Frank Darabont", "Steven Spielberg", "Martin Scorsese", "Clint Eastwood"], a: "Frank Darabont", c: "entertainment", d: "hard", p: 20, t: 35 },
    { q: "Which band released the album 'Abbey Road'?", o: ["The Rolling Stones", "The Beatles", "Pink Floyd", "Led Zeppelin"], a: "The Beatles", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Who wrote 'The Catcher in the Rye'?", o: ["J.D. Salinger", "Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck"], a: "J.D. Salinger", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Which movie features the quote 'Here's looking at you, kid'?", o: ["Gone with the Wind", "Casablanca", "The Maltese Falcon", "Citizen Kane"], a: "Casablanca", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Who played the Joker in 'The Dark Knight'?", o: ["Jack Nicholson", "Joaquin Phoenix", "Heath Ledger", "Jared Leto"], a: "Heath Ledger", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Which musical features the song 'Memory'?", o: ["Cats", "The Phantom of the Opera", "Les Misérables", "Evita"], a: "Cats", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Who wrote 'Brave New World'?", o: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Philip K. Dick"], a: "Aldous Huxley", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Which movie won the Oscar for Best Picture in 2019?", o: ["Roma", "The Favourite", "Green Book", "A Star Is Born"], a: "Green Book", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Who sang 'Imagine'?", o: ["Paul McCartney", "John Lennon", "George Harrison", "Ringo Starr"], a: "John Lennon", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Which TV series features Sheldon Cooper?", o: ["Friends", "How I Met Your Mother", "The Big Bang Theory", "Two and a Half Men"], a: "The Big Bang Theory", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Who directed 'Jurassic Park'?", o: ["James Cameron", "Steven Spielberg", "George Lucas", "Ridley Scott"], a: "Steven Spielberg", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Which artist is known for the 'Campbell's Soup Cans'?", o: ["Roy Lichtenstein", "Andy Warhol", "Jackson Pollock", "Keith Haring"], a: "Andy Warhol", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Who wrote 'The Lord of the Rings'?", o: ["C.S. Lewis", "J.R.R. Tolkien", "George R.R. Martin", "Terry Pratchett"], a: "J.R.R. Tolkien", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Which movie features the character Hannibal Lecter?", o: ["Seven", "The Silence of the Lambs", "Zodiac", "Prisoners"], a: "The Silence of the Lambs", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Who composed 'Moonlight Sonata'?", o: ["Mozart", "Beethoven", "Chopin", "Bach"], a: "Beethoven", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Which TV show is set in the town of Springfield?", o: ["Family Guy", "South Park", "The Simpsons", "American Dad"], a: "The Simpsons", c: "entertainment", d: "easy", p: 10, t: 15 },
    { q: "Who painted 'The Persistence of Memory'?", o: ["Pablo Picasso", "Salvador Dalí", "René Magritte", "Joan Miró"], a: "Salvador Dalí", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Which movie features the quote 'I'll be back'?", o: ["Predator", "The Terminator", "Total Recall", "Commando"], a: "The Terminator", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Who sang 'Billie Jean'?", o: ["Prince", "Michael Jackson", "Stevie Wonder", "Lionel Richie"], a: "Michael Jackson", c: "entertainment", d: "easy", p: 10, t: 15 },
    { q: "Which Shakespeare play features the character Macbeth?", o: ["Hamlet", "Macbeth", "King Lear", "Julius Caesar"], a: "Macbeth", c: "entertainment", d: "easy", p: 10, t: 15 },
    { q: "Who directed 'Avatar'?", o: ["Peter Jackson", "James Cameron", "Steven Spielberg", "Ridley Scott"], a: "James Cameron", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Which band released 'Hotel California'?", o: ["The Eagles", "Fleetwood Mac", "The Doors", "Lynyrd Skynyrd"], a: "The Eagles", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Who wrote 'The Hobbit'?", o: ["C.S. Lewis", "J.R.R. Tolkien", "George R.R. Martin", "Philip Pullman"], a: "J.R.R. Tolkien", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Which movie features the character Vito Corleone?", o: ["Goodfellas", "The Godfather", "Casino", "Scarface"], a: "The Godfather", c: "entertainment", d: "easy", p: 10, t: 20 },
    { q: "Who composed the opera 'The Magic Flute'?", o: ["Beethoven", "Mozart", "Verdi", "Wagner"], a: "Mozart", c: "entertainment", d: "hard", p: 20, t: 35 },
    { q: "Which TV series features the character Tony Soprano?", o: ["The Wire", "Breaking Bad", "The Sopranos", "Mad Men"], a: "The Sopranos", c: "entertainment", d: "medium", p: 15, t: 25 },
    { q: "Who painted 'Girl with a Pearl Earring'?", o: ["Rembrandt", "Johannes Vermeer", "Frans Hals", "Jan Steen"], a: "Johannes Vermeer", c: "entertainment", d: "hard", p: 20, t: 35 },
    { q: "Which movie won the Oscar for Best Picture in 2017?", o: ["La La Land", "Moonlight", "Manchester by the Sea", "Arrival"], a: "Moonlight", c: "entertainment", d: "medium", p: 15, t: 30 },
    { q: "Who sang 'Respect'?", o: ["Diana Ross", "Aretha Franklin", "Tina Turner", "Whitney Houston"], a: "Aretha Franklin", c: "entertainment", d: "medium", p: 15, t: 25 },

    // SPORTS - 50 questions
    { q: "How many players are on a basketball team on the court?", o: ["4", "5", "6", "7"], a: "5", c: "sports", d: "easy", p: 10, t: 15 },
    { q: "Which country won the FIFA World Cup in 2018?", o: ["Germany", "Brazil", "France", "Argentina"], a: "France", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "What is the maximum score in a single frame of bowling?", o: ["100", "200", "300", "400"], a: "300", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "Who has won the most Olympic gold medals?", o: ["Usain Bolt", "Michael Phelps", "Carl Lewis", "Mark Spitz"], a: "Michael Phelps", c: "sports", d: "medium", p: 15, t: 30 },
    { q: "In which sport would you perform a 'slam dunk'?", o: ["Volleyball", "Basketball", "Tennis", "Badminton"], a: "Basketball", c: "sports", d: "easy", p: 10, t: 15 },
    { q: "How many Grand Slam tournaments are there in tennis per year?", o: ["2", "3", "4", "5"], a: "4", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "Which country hosted the 2016 Summer Olympics?", o: ["China", "UK", "Brazil", "Russia"], a: "Brazil", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "What is the national sport of Japan?", o: ["Judo", "Karate", "Sumo Wrestling", "Kendo"], a: "Sumo Wrestling", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "How many points is a touchdown worth in American football?", o: ["3", "6", "7", "10"], a: "6", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "Which tennis player has won the most Grand Slam titles (Women's Singles)?", o: ["Serena Williams", "Margaret Court", "Steffi Graf", "Martina Navratilova"], a: "Margaret Court", c: "sports", d: "hard", p: 20, t: 35 },
    { q: "In which sport do you use a puck?", o: ["Field Hockey", "Ice Hockey", "Lacrosse", "Polo"], a: "Ice Hockey", c: "sports", d: "easy", p: 10, t: 15 },
    { q: "How long is an Olympic swimming pool in meters?", o: ["25m", "50m", "75m", "100m"], a: "50m", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "Which country has won the most Cricket World Cups?", o: ["India", "Australia", "West Indies", "England"], a: "Australia", c: "sports", d: "medium", p: 15, t: 30 },
    { q: "What is the diameter of a basketball hoop in inches?", o: ["16", "18", "20", "22"], a: "18", c: "sports", d: "hard", p: 20, t: 30 },
    { q: "Which boxer was known as 'The Greatest'?", o: ["Mike Tyson", "Muhammad Ali", "Joe Frazier", "George Foreman"], a: "Muhammad Ali", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "How many players are on a rugby union team?", o: ["11", "13", "15", "17"], a: "15", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "Which country won the first FIFA World Cup?", o: ["Brazil", "Argentina", "Uruguay", "Italy"], a: "Uruguay", c: "sports", d: "hard", p: 20, t: 35 },
    { q: "What is the highest possible break in snooker?", o: ["147", "150", "155", "160"], a: "147", c: "sports", d: "hard", p: 20, t: 30 },
    { q: "In which sport would you perform a 'birdie'?", o: ["Badminton", "Golf", "Tennis", "Squash"], a: "Golf", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "How many rings are on the Olympic flag?", o: ["3", "4", "5", "6"], a: "5", c: "sports", d: "easy", p: 10, t: 15 },
    { q: "Which footballer has won the most Ballon d'Or awards?", o: ["Cristiano Ronaldo", "Lionel Messi", "Michel Platini", "Johan Cruyff"], a: "Lionel Messi", c: "sports", d: "medium", p: 15, t: 30 },
    { q: "What is the national sport of Canada?", o: ["Ice Hockey", "Lacrosse", "Both Ice Hockey and Lacrosse", "Basketball"], a: "Both Ice Hockey and Lacrosse", c: "sports", d: "hard", p: 20, t: 35 },
    { q: "How many holes are played in a standard round of golf?", o: ["9", "12", "18", "24"], a: "18", c: "sports", d: "easy", p: 10, t: 15 },
    { q: "Which country has won the most Rugby World Cups?", o: ["Australia", "New Zealand", "South Africa", "England"], a: "New Zealand", c: "sports", d: "medium", p: 15, t: 30 },
    { q: "What is the maximum number of sets in a men's Grand Slam tennis match?", o: ["3", "4", "5", "6"], a: "5", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "Which athlete is known as 'Lightning Bolt'?", o: ["Carl Lewis", "Usain Bolt", "Michael Johnson", "Tyson Gay"], a: "Usain Bolt", c: "sports", d: "easy", p: 10, t: 15 },
    { q: "How many players are on a volleyball team on the court?", o: ["4", "5", "6", "7"], a: "6", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "Which country hosted the first modern Olympic Games?", o: ["France", "Greece", "UK", "USA"], a: "Greece", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "What is the length of a marathon in kilometers?", o: ["40.2 km", "42.195 km", "44.5 km", "46 km"], a: "42.195 km", c: "sports", d: "medium", p: 15, t: 30 },
    { q: "Which NBA team has won the most championships?", o: ["Los Angeles Lakers", "Boston Celtics", "Chicago Bulls", "Golden State Warriors"], a: "Boston Celtics", c: "sports", d: "medium", p: 15, t: 30 },
    { q: "In which sport do you use a shuttlecock?", o: ["Tennis", "Squash", "Badminton", "Table Tennis"], a: "Badminton", c: "sports", d: "easy", p: 10, t: 15 },
    { q: "How many minutes are in a soccer match (excluding extra time)?", o: ["80", "90", "100", "120"], a: "90", c: "sports", d: "easy", p: 10, t: 15 },
    { q: "Which golfer has won the most major championships?", o: ["Tiger Woods", "Jack Nicklaus", "Arnold Palmer", "Gary Player"], a: "Jack Nicklaus", c: "sports", d: "medium", p: 15, t: 30 },
    { q: "What is the national sport of India?", o: ["Cricket", "Field Hockey", "Kabaddi", "Wrestling"], a: "Field Hockey", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "How many points is a field goal worth in basketball?", o: ["1", "2", "3", "Depends on distance"], a: "Depends on distance", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "Which country won the first Cricket World Cup?", o: ["Australia", "West Indies", "England", "India"], a: "West Indies", c: "sports", d: "hard", p: 20, t: 35 },
    { q: "What is the height of a regulation NBA basketball hoop in feet?", o: ["8", "9", "10", "11"], a: "10", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "Which Formula 1 driver has won the most World Championships?", o: ["Lewis Hamilton", "Michael Schumacher", "Ayrton Senna", "Sebastian Vettel"], a: "Lewis Hamilton", c: "sports", d: "medium", p: 15, t: 30 },
    { q: "In which sport would you perform a 'spike'?", o: ["Tennis", "Volleyball", "Badminton", "Squash"], a: "Volleyball", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "How many periods are in an ice hockey game?", o: ["2", "3", "4", "5"], a: "3", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "Which country won the 2019 Cricket World Cup?", o: ["India", "Australia", "England", "New Zealand"], a: "England", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "What is the weight of a regulation bowling ball in pounds (maximum)?", o: ["12", "14", "16", "18"], a: "16", c: "sports", d: "hard", p: 20, t: 30 },
    { q: "Which swimmer is known as the 'Flying Fish'?", o: ["Ian Thorpe", "Michael Phelps", "Ryan Lochte", "Mark Spitz"], a: "Michael Phelps", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "In which sport do you use a foil, épée, or sabre?", o: ["Fencing", "Archery", "Javelin", "Shooting"], a: "Fencing", c: "sports", d: "medium", p: 15, t: 25 },
    { q: "How many innings are in a standard baseball game?", o: ["7", "8", "9", "10"], a: "9", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "Which country has won the most Olympic gold medals in total?", o: ["China", "Russia", "USA", "Germany"], a: "USA", c: "sports", d: "medium", p: 15, t: 30 },
    { q: "What is the national sport of Argentina?", o: ["Football", "Rugby", "Polo", "Pato"], a: "Pato", c: "sports", d: "hard", p: 20, t: 35 },
    { q: "How many majors has Tiger Woods won?", o: ["12", "14", "15", "18"], a: "15", c: "sports", d: "medium", p: 15, t: 30 },
    { q: "Which country won the 2022 FIFA World Cup?", o: ["France", "Argentina", "Brazil", "Germany"], a: "Argentina", c: "sports", d: "easy", p: 10, t: 20 },
    { q: "In which sport would you perform a 'hat-trick'?", o: ["Cricket", "Football", "Both Cricket and Football", "Hockey"], a: "Both Cricket and Football", c: "sports", d: "medium", p: 15, t: 25 },

    // ASTRONOMY - 40 questions
    { q: "How many planets are in our solar system?", o: ["7", "8", "9", "10"], a: "8", c: "astronomy", d: "easy", p: 10, t: 15 },
    { q: "What is the hottest planet in our solar system?", o: ["Mercury", "Venus", "Mars", "Jupiter"], a: "Venus", c: "astronomy", d: "medium", p: 15, t: 25 },
    { q: "Which planet is known for its Great Red Spot?", o: ["Mars", "Jupiter", "Saturn", "Neptune"], a: "Jupiter", c: "astronomy", d: "medium", p: 15, t: 25 },
    { q: "What is the name of the first artificial satellite?", o: ["Explorer 1", "Sputnik 1", "Vanguard 1", "Luna 1"], a: "Sputnik 1", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "How long does it take for light from the Sun to reach Earth?", o: ["8 minutes", "8 hours", "8 days", "8 seconds"], a: "8 minutes", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "Which planet has the most moons?", o: ["Jupiter", "Saturn", "Uranus", "Neptune"], a: "Saturn", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "What is the name of Mars' largest moon?", o: ["Titan", "Phobos", "Europa", "Ganymede"], a: "Phobos", c: "astronomy", d: "hard", p: 20, t: 30 },
    { q: "Which constellation contains the North Star?", o: ["Ursa Major", "Ursa Minor", "Orion", "Cassiopeia"], a: "Ursa Minor", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "What is the name of the galaxy closest to the Milky Way?", o: ["Andromeda", "Triangulum", "Sombrero", "Whirlpool"], a: "Andromeda", c: "astronomy", d: "medium", p: 15, t: 25 },
    { q: "Which planet rotates on its side?", o: ["Neptune", "Uranus", "Saturn", "Jupiter"], a: "Uranus", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "What is a supernova?", o: ["A new star", "An exploding star", "A dying star", "A black hole"], a: "An exploding star", c: "astronomy", d: "medium", p: 15, t: 25 },
    { q: "Which planet has the shortest day?", o: ["Mercury", "Venus", "Earth", "Jupiter"], a: "Jupiter", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "What is the name of Saturn's largest moon?", o: ["Titan", "Rhea", "Iapetus", "Enceladus"], a: "Titan", c: "astronomy", d: "medium", p: 15, t: 25 },
    { q: "Which space telescope was launched in 1990?", o: ["Hubble", "James Webb", "Spitzer", "Kepler"], a: "Hubble", c: "astronomy", d: "medium", p: 15, t: 25 },
    { q: "What is the Kuiper Belt?", o: ["An asteroid belt", "A region beyond Neptune", "A type of comet", "A planetary ring"], a: "A region beyond Neptune", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "Which planet has the longest year?", o: ["Uranus", "Neptune", "Saturn", "Jupiter"], a: "Neptune", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "What is the name of Jupiter's largest moon?", o: ["Io", "Europa", "Ganymede", "Callisto"], a: "Ganymede", c: "astronomy", d: "medium", p: 15, t: 25 },
    { q: "Which astronaut was the second person to walk on the Moon?", o: ["Neil Armstrong", "Buzz Aldrin", "Michael Collins", "Alan Shepard"], a: "Buzz Aldrin", c: "astronomy", d: "easy", p: 10, t: 20 },
    { q: "What is a light-year?", o: ["A unit of time", "A unit of distance", "A unit of speed", "A unit of mass"], a: "A unit of distance", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "Which planet is closest to the Sun?", o: ["Venus", "Mercury", "Earth", "Mars"], a: "Mercury", c: "astronomy", d: "easy", p: 10, t: 15 },
    { q: "What is the name of the rover that landed on Mars in 2021?", o: ["Curiosity", "Perseverance", "Opportunity", "Spirit"], a: "Perseverance", c: "astronomy", d: "medium", p: 15, t: 25 },
    { q: "Which constellation is known as 'The Hunter'?", o: ["Orion", "Sagittarius", "Hercules", "Perseus"], a: "Orion", c: "astronomy", d: "easy", p: 10, t: 20 },
    { q: "What is the Great Dark Spot?", o: ["A feature on Neptune", "A feature on Jupiter", "A feature on Saturn", "A feature on Uranus"], a: "A feature on Neptune", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "Which planet has the most extreme temperature variations?", o: ["Mercury", "Venus", "Mars", "Earth"], a: "Mercury", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "What is the name of the first space station?", o: ["Mir", "Skylab", "Salyut 1", "ISS"], a: "Salyut 1", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "Which dwarf planet was discovered in 2005?", o: ["Pluto", "Eris", "Ceres", "Makemake"], a: "Eris", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "What is the asteroid belt located between?", o: ["Earth and Mars", "Mars and Jupiter", "Jupiter and Saturn", "Saturn and Uranus"], a: "Mars and Jupiter", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "Which planet has a day longer than its year?", o: ["Mercury", "Venus", "Mars", "Jupiter"], a: "Venus", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "What is the name of the largest volcano in the solar system?", o: ["Mount Everest", "Olympus Mons", "Mauna Kea", "Mount Vesuvius"], a: "Olympus Mons", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "Which space probe was the first to leave the solar system?", o: ["Voyager 1", "Voyager 2", "Pioneer 10", "New Horizons"], a: "Voyager 1", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "What is the name of the brightest star in the night sky?", o: ["Polaris", "Sirius", "Betelgeuse", "Vega"], a: "Sirius", c: "astronomy", d: "medium", p: 15, t: 25 },
    { q: "Which planet has the fastest winds?", o: ["Jupiter", "Saturn", "Uranus", "Neptune"], a: "Neptune", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "What is a pulsar?", o: ["A rotating neutron star", "A type of black hole", "A dying star", "A new star"], a: "A rotating neutron star", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "Which moon in our solar system has active volcanoes?", o: ["Europa", "Titan", "Io", "Enceladus"], a: "Io", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "What is the name of the boundary around a black hole?", o: ["Event Horizon", "Schwarzschild Radius", "Singularity", "Photon Sphere"], a: "Event Horizon", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "Which planet has the coldest recorded temperature?", o: ["Neptune", "Uranus", "Pluto", "Saturn"], a: "Uranus", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "What is the name of the first American in space?", o: ["John Glenn", "Alan Shepard", "Neil Armstrong", "Buzz Aldrin"], a: "Alan Shepard", c: "astronomy", d: "medium", p: 15, t: 30 },
    { q: "Which constellation contains the star Betelgeuse?", o: ["Orion", "Taurus", "Gemini", "Canis Major"], a: "Orion", c: "astronomy", d: "medium", p: 15, t: 25 },
    { q: "What is the name of the largest known star?", o: ["Betelgeuse", "UY Scuti", "VY Canis Majoris", "Antares"], a: "UY Scuti", c: "astronomy", d: "hard", p: 20, t: 35 },
    { q: "Which space mission first landed humans on the Moon?", o: ["Apollo 10", "Apollo 11", "Apollo 12", "Apollo 13"], a: "Apollo 11", c: "astronomy", d: "easy", p: 10, t: 20 },

    // GENERAL KNOWLEDGE - 50 questions
    { q: "What is the tallest building in the world?", o: ["Shanghai Tower", "Burj Khalifa", "Abraj Al-Bait", "Ping An Finance Centre"], a: "Burj Khalifa", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many colors are in a rainbow?", o: ["5", "6", "7", "8"], a: "7", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the largest desert in the world?", o: ["Sahara", "Arabian", "Gobi", "Antarctic"], a: "Antarctic", c: "general", d: "hard", p: 20, t: 30 },
    { q: "How many days are in a leap year?", o: ["364", "365", "366", "367"], a: "366", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the most spoken language in the world by native speakers?", o: ["English", "Spanish", "Mandarin Chinese", "Hindi"], a: "Mandarin Chinese", c: "general", d: "medium", p: 15, t: 30 },
    { q: "How many bones does a shark have?", o: ["0", "50", "100", "200"], a: "0", c: "general", d: "medium", p: 15, t: 25 },
    { q: "What is the largest living species of lizard?", o: ["Iguana", "Monitor Lizard", "Komodo Dragon", "Crocodile"], a: "Komodo Dragon", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many strings does a standard guitar have?", o: ["4", "5", "6", "7"], a: "6", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the national flower of Japan?", o: ["Rose", "Tulip", "Cherry Blossom", "Lotus"], a: "Cherry Blossom", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many sides does a hexagon have?", o: ["5", "6", "7", "8"], a: "6", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the largest cat species?", o: ["Lion", "Tiger", "Jaguar", "Leopard"], a: "Tiger", c: "general", d: "easy", p: 10, t: 20 },
    { q: "How many minutes are in a day?", o: ["1440", "1400", "1480", "1500"], a: "1440", c: "general", d: "medium", p: 15, t: 25 },
    { q: "What is the national bird of the United States?", o: ["Eagle", "Bald Eagle", "Golden Eagle", "Hawk"], a: "Bald Eagle", c: "general", d: "easy", p: 10, t: 20 },
    { q: "How many teeth does an adult human have (including wisdom teeth)?", o: ["28", "30", "32", "34"], a: "32", c: "general", d: "easy", p: 10, t: 20 },
    { q: "What is the largest land animal?", o: ["Rhino", "Hippo", "Elephant", "Giraffe"], a: "Elephant", c: "general", d: "easy", p: 10, t: 15 },
    { q: "How many cards are in a standard deck?", o: ["48", "50", "52", "54"], a: "52", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the fastest land animal?", o: ["Lion", "Cheetah", "Leopard", "Gazelle"], a: "Cheetah", c: "general", d: "easy", p: 10, t: 15 },
    { q: "How many hours are in a week?", o: ["156", "164", "168", "172"], a: "168", c: "general", d: "medium", p: 15, t: 25 },
    { q: "What is the national animal of Australia?", o: ["Koala", "Kangaroo", "Emu", "Platypus"], a: "Kangaroo", c: "general", d: "easy", p: 10, t: 20 },
    { q: "How many degrees are in a circle?", o: ["180", "270", "360", "450"], a: "360", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the largest bird in the world?", o: ["Emu", "Ostrich", "Cassowary", "Rhea"], a: "Ostrich", c: "general", d: "easy", p: 10, t: 20 },
    { q: "How many months have 31 days?", o: ["5", "6", "7", "8"], a: "7", c: "general", d: "easy", p: 10, t: 20 },
    { q: "What is the slowest animal in the world?", o: ["Snail", "Sloth", "Tortoise", "Koala"], a: "Sloth", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many seconds are in an hour?", o: ["3000", "3600", "4000", "4200"], a: "3600", c: "general", d: "easy", p: 10, t: 20 },
    { q: "What is the national sport of England?", o: ["Football", "Rugby", "Cricket", "Tennis"], a: "Cricket", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many legs does a spider have?", o: ["6", "8", "10", "12"], a: "8", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the largest ocean in the world?", o: ["Atlantic", "Indian", "Arctic", "Pacific"], a: "Pacific", c: "general", d: "easy", p: 10, t: 15 },
    { q: "How many zeros are in one million?", o: ["5", "6", "7", "8"], a: "6", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the fastest bird in the world?", o: ["Eagle", "Falcon", "Hawk", "Peregrine Falcon"], a: "Peregrine Falcon", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many days are in February during a leap year?", o: ["28", "29", "30", "31"], a: "29", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the national flower of England?", o: ["Daffodil", "Thistle", "Rose", "Shamrock"], a: "Rose", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many planets in our solar system have rings?", o: ["1", "2", "3", "4"], a: "4", c: "general", d: "hard", p: 20, t: 30 },
    { q: "What is the largest snake in the world?", o: ["Python", "Anaconda", "Boa Constrictor", "King Cobra"], a: "Anaconda", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many sides does a pentagon have?", o: ["4", "5", "6", "7"], a: "5", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the national animal of China?", o: ["Dragon", "Panda", "Tiger", "Lion"], a: "Panda", c: "general", d: "easy", p: 10, t: 20 },
    { q: "How many letters are in the English alphabet?", o: ["24", "25", "26", "27"], a: "26", c: "general", d: "easy", p: 10, t: 10 },
    { q: "What is the largest fish in the world?", o: ["Great White Shark", "Whale Shark", "Manta Ray", "Basking Shark"], a: "Whale Shark", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many weeks are in a year?", o: ["50", "51", "52", "53"], a: "52", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the national tree of India?", o: ["Neem", "Banyan", "Peepal", "Mango"], a: "Banyan", c: "general", d: "hard", p: 20, t: 30 },
    { q: "How many eyes does a bee have?", o: ["2", "3", "4", "5"], a: "5", c: "general", d: "hard", p: 20, t: 30 },
    { q: "What is the largest rodent in the world?", o: ["Beaver", "Capybara", "Porcupine", "Muskrat"], a: "Capybara", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many sides does an octagon have?", o: ["6", "7", "8", "9"], a: "8", c: "general", d: "easy", p: 10, t: 15 },
    { q: "What is the national animal of Scotland?", o: ["Lion", "Stag", "Unicorn", "Eagle"], a: "Unicorn", c: "general", d: "hard", p: 20, t: 30 },
    { q: "How many hearts does an octopus have?", o: ["1", "2", "3", "4"], a: "3", c: "general", d: "hard", p: 20, t: 30 },
    { q: "What is the largest primate in the world?", o: ["Chimpanzee", "Orangutan", "Gorilla", "Baboon"], a: "Gorilla", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many time zones does Russia have?", o: ["7", "9", "11", "13"], a: "11", c: "general", d: "hard", p: 20, t: 35 },
    { q: "What is the national flower of the Netherlands?", o: ["Rose", "Tulip", "Daffodil", "Lily"], a: "Tulip", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many chambers does a human stomach have?", o: ["1", "2", "3", "4"], a: "1", c: "general", d: "medium", p: 15, t: 25 },
    { q: "What is the largest bear species?", o: ["Grizzly Bear", "Polar Bear", "Kodiak Bear", "Black Bear"], a: "Polar Bear", c: "general", d: "medium", p: 15, t: 25 },
    { q: "How many years are in a decade?", o: ["5", "10", "15", "20"], a: "10", c: "general", d: "easy", p: 10, t: 10 }
];

// Convert compact format to full format
const expandedQuestions = batch2Questions.map(q => ({
    question: q.q,
    options: q.o,
    correctAnswer: q.a,
    category: q.c,
    difficulty: q.d,
    points: q.p,
    timeLimit: q.t
}));

console.log(`✅ Batch 2 contains ${expandedQuestions.length} questions`);
export default expandedQuestions;
