// Script to generate additional questions for the quiz portal
import fs from 'fs';

const additionalQuestions = [
    // GEOGRAPHY - 60 questions
    { question: "What is the capital of Canada?", options: ["Toronto", "Ottawa", "Vancouver", "Montreal"], correctAnswer: "Ottawa", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which desert is the largest in the world?", options: ["Sahara", "Arabian", "Gobi", "Antarctic"], correctAnswer: "Antarctic", category: "geography", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "What is the longest river in Europe?", options: ["Danube", "Rhine", "Volga", "Thames"], correctAnswer: "Volga", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "Which country has the most islands?", options: ["Indonesia", "Philippines", "Sweden", "Japan"], correctAnswer: "Sweden", category: "geography", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "What is the capital of Brazil?", options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], correctAnswer: "Brasília", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "Mount Kilimanjaro is located in which country?", options: ["Kenya", "Tanzania", "Uganda", "Ethiopia"], correctAnswer: "Tanzania", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the smallest ocean?", options: ["Atlantic", "Indian", "Arctic", "Southern"], correctAnswer: "Arctic", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which European city is known as the 'City of Canals'?", options: ["Amsterdam", "Venice", "Bruges", "Stockholm"], correctAnswer: "Venice", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "The Sahara Desert is primarily located in which continent?", options: ["Asia", "Africa", "Australia", "South America"], correctAnswer: "Africa", category: "geography", difficulty: "easy", points: 10, timeLimit: 15 },
    { question: "What is the capital of Egypt?", options: ["Alexandria", "Cairo", "Giza", "Luxor"], correctAnswer: "Cairo", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which country is known as the 'Land of Fire and Ice'?", options: ["Norway", "Iceland", "Finland", "Greenland"], correctAnswer: "Iceland", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "Lake Baikal, the deepest lake in the world, is in which country?", options: ["Canada", "Russia", "Mongolia", "China"], correctAnswer: "Russia", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the capital of New Zealand?", options: ["Auckland", "Wellington", "Christchurch", "Hamilton"], correctAnswer: "Wellington", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "The Amazon Rainforest is primarily located in which country?", options: ["Colombia", "Peru", "Brazil", "Venezuela"], correctAnswer: "Brazil", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which strait separates Europe and Africa?", options: ["Bering Strait", "Strait of Gibraltar", "Strait of Hormuz", "Bosphorus"], correctAnswer: "Strait of Gibraltar", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the capital of Thailand?", options: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"], correctAnswer: "Bangkok", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which mountain range separates Europe and Asia?", options: ["Alps", "Himalayas", "Ural Mountains", "Caucasus"], correctAnswer: "Ural Mountains", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the largest island in the Mediterranean Sea?", options: ["Crete", "Cyprus", "Sicily", "Sardinia"], correctAnswer: "Sicily", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "Which African country was formerly known as Abyssinia?", options: ["Egypt", "Ethiopia", "Sudan", "Somalia"], correctAnswer: "Ethiopia", category: "geography", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "What is the capital of South Korea?", options: ["Busan", "Seoul", "Incheon", "Daegu"], correctAnswer: "Seoul", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "The Andes mountain range is located in which continent?", options: ["Africa", "Asia", "South America", "North America"], correctAnswer: "South America", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which sea is the saltiest natural lake?", options: ["Red Sea", "Dead Sea", "Caspian Sea", "Black Sea"], correctAnswer: "Dead Sea", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What is the capital of Argentina?", options: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"], correctAnswer: "Buenos Aires", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which country has the longest coastline in the world?", options: ["Australia", "Russia", "Canada", "Indonesia"], correctAnswer: "Canada", category: "geography", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "The Suez Canal connects which two seas?", options: ["Red Sea and Mediterranean", "Black Sea and Caspian", "Arabian Sea and Red Sea", "Mediterranean and Black Sea"], correctAnswer: "Red Sea and Mediterranean", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the capital of Norway?", options: ["Bergen", "Oslo", "Trondheim", "Stavanger"], correctAnswer: "Oslo", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which country is both in Europe and Asia?", options: ["Russia", "Turkey", "Kazakhstan", "All of the above"], correctAnswer: "All of the above", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the capital of Switzerland?", options: ["Zurich", "Geneva", "Bern", "Basel"], correctAnswer: "Bern", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "The Great Barrier Reef is located off the coast of which country?", options: ["Indonesia", "Philippines", "Australia", "New Zealand"], correctAnswer: "Australia", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which river flows through Paris?", options: ["Thames", "Rhine", "Seine", "Danube"], correctAnswer: "Seine", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the capital of Vietnam?", options: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hue"], correctAnswer: "Hanoi", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "Which continent has no permanent human population?", options: ["Antarctica", "Arctic", "Greenland", "Iceland"], correctAnswer: "Antarctica", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the capital of Austria?", options: ["Salzburg", "Vienna", "Innsbruck", "Graz"], correctAnswer: "Vienna", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "The Taj Mahal is located in which Indian city?", options: ["Delhi", "Mumbai", "Agra", "Jaipur"], correctAnswer: "Agra", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "Which country is known as the 'Pearl of the Orient'?", options: ["Thailand", "Philippines", "Singapore", "Malaysia"], correctAnswer: "Philippines", category: "geography", difficulty: "hard", points: 20, timeLimit: 30 },
    { question: "What is the capital of Chile?", options: ["Valparaíso", "Santiago", "Concepción", "La Serena"], correctAnswer: "Santiago", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "Which ocean is the Mariana Trench located in?", options: ["Atlantic", "Indian", "Pacific", "Southern"], correctAnswer: "Pacific", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the capital of Portugal?", options: ["Porto", "Lisbon", "Faro", "Braga"], correctAnswer: "Lisbon", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which African country has the largest population?", options: ["Egypt", "Ethiopia", "Nigeria", "South Africa"], correctAnswer: "Nigeria", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "The Panama Canal connects which two oceans?", options: ["Atlantic and Indian", "Pacific and Indian", "Atlantic and Pacific", "Arctic and Pacific"], correctAnswer: "Atlantic and Pacific", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the capital of Denmark?", options: ["Aarhus", "Copenhagen", "Odense", "Aalborg"], correctAnswer: "Copenhagen", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which country has the most time zones?", options: ["Russia", "USA", "France", "China"], correctAnswer: "France", category: "geography", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "What is the capital of Peru?", options: ["Cusco", "Lima", "Arequipa", "Trujillo"], correctAnswer: "Lima", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "The Statue of Liberty was a gift from which country?", options: ["England", "France", "Spain", "Italy"], correctAnswer: "France", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which river is the longest in Asia?", options: ["Ganges", "Mekong", "Yangtze", "Yellow River"], correctAnswer: "Yangtze", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the capital of Malaysia?", options: ["Kuala Lumpur", "Penang", "Johor Bahru", "Malacca"], correctAnswer: "Kuala Lumpur", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which country is home to the ancient city of Petra?", options: ["Egypt", "Jordan", "Syria", "Lebanon"], correctAnswer: "Jordan", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the capital of Finland?", options: ["Tampere", "Helsinki", "Turku", "Espoo"], correctAnswer: "Helsinki", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "The Galapagos Islands belong to which country?", options: ["Colombia", "Peru", "Ecuador", "Chile"], correctAnswer: "Ecuador", category: "geography", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the capital of Ireland?", options: ["Cork", "Dublin", "Galway", "Limerick"], correctAnswer: "Dublin", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Which sea separates Saudi Arabia from Africa?", options: ["Arabian Sea", "Red Sea", "Mediterranean Sea", "Dead Sea"], correctAnswer: "Red Sea", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What is the capital of Morocco?", options: ["Casablanca", "Marrakech", "Rabat", "Fez"], correctAnswer: "Rabat", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "Which country is the largest producer of coffee?", options: ["Colombia", "Vietnam", "Brazil", "Ethiopia"], correctAnswer: "Brazil", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What is the capital of Poland?", options: ["Krakow", "Warsaw", "Gdansk", "Wroclaw"], correctAnswer: "Warsaw", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "The Colosseum is located in which city?", options: ["Athens", "Rome", "Venice", "Florence"], correctAnswer: "Rome", category: "geography", difficulty: "easy", points: 10, timeLimit: 15 },
    { question: "Which country has the most UNESCO World Heritage Sites?", options: ["China", "Italy", "Spain", "France"], correctAnswer: "Italy", category: "geography", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "What is the capital of Turkey?", options: ["Istanbul", "Ankara", "Izmir", "Antalya"], correctAnswer: "Ankara", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "Which country is known as the 'Emerald Isle'?", options: ["Scotland", "Ireland", "Iceland", "New Zealand"], correctAnswer: "Ireland", category: "geography", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What is the capital of Greece?", options: ["Thessaloniki", "Athens", "Sparta", "Corinth"], correctAnswer: "Athens", category: "geography", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "The Eiffel Tower is located in which city?", options: ["London", "Paris", "Berlin", "Rome"], correctAnswer: "Paris", category: "geography", difficulty: "easy", points: 10, timeLimit: 15 },

    // SCIENCE & TECHNOLOGY - 80 questions
    { question: "What is the chemical symbol for sodium?", options: ["S", "So", "Na", "Sd"], correctAnswer: "Na", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Who invented the telephone?", options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], correctAnswer: "Alexander Graham Bell", category: "science", difficulty: "easy", points: 10, timeLimit: 25 },
    { question: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"], correctAnswer: "Mitochondria", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Dinitrogen Acid", "Dynamic Nuclear Acid", "Dextrose Nucleic Acid"], correctAnswer: "Deoxyribonucleic Acid", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the speed of sound in air at sea level?", options: ["343 m/s", "300 m/s", "400 m/s", "500 m/s"], correctAnswer: "343 m/s", category: "science", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "Who developed the theory of relativity?", options: ["Isaac Newton", "Albert Einstein", "Stephen Hawking", "Niels Bohr"], correctAnswer: "Albert Einstein", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the chemical formula for water?", options: ["H2O", "CO2", "O2", "H2O2"], correctAnswer: "H2O", category: "science", difficulty: "easy", points: 10, timeLimit: 15 },
    { question: "What is the largest organ in the human body?", options: ["Liver", "Brain", "Skin", "Heart"], correctAnswer: "Skin", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What programming language is known as the 'language of the web'?", options: ["Python", "Java", "JavaScript", "C++"], correctAnswer: "JavaScript", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Unit"], correctAnswer: "Central Processing Unit", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Who is known as the father of modern physics?", options: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Niels Bohr"], correctAnswer: "Galileo Galilei", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the atomic number of carbon?", options: ["4", "6", "8", "12"], correctAnswer: "6", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What does HTTP stand for?", options: ["HyperText Transfer Protocol", "High Transfer Text Protocol", "HyperText Transmission Process", "Home Tool Transfer Protocol"], correctAnswer: "HyperText Transfer Protocol", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the most abundant gas in Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctAnswer: "Nitrogen", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "Who invented the World Wide Web?", options: ["Bill Gates", "Steve Jobs", "Tim Berners-Lee", "Mark Zuckerberg"], correctAnswer: "Tim Berners-Lee", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the chemical symbol for potassium?", options: ["P", "Po", "K", "Pt"], correctAnswer: "K", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What does AI stand for in technology?", options: ["Automated Intelligence", "Artificial Intelligence", "Advanced Integration", "Automatic Interface"], correctAnswer: "Artificial Intelligence", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "How many bones are in the adult human body?", options: ["186", "206", "226", "246"], correctAnswer: "206", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the study of earthquakes called?", options: ["Meteorology", "Seismology", "Geology", "Volcanology"], correctAnswer: "Seismology", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "Who invented the light bulb?", options: ["Nikola Tesla", "Thomas Edison", "Benjamin Franklin", "Alexander Graham Bell"], correctAnswer: "Thomas Edison", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the chemical formula for table salt?", options: ["NaCl", "KCl", "CaCl2", "MgCl2"], correctAnswer: "NaCl", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What does RAM stand for in computers?", options: ["Random Access Memory", "Read Access Memory", "Rapid Application Memory", "Remote Access Module"], correctAnswer: "Random Access Memory", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the pH of pure water?", options: ["5", "7", "9", "11"], correctAnswer: "7", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "Who discovered gravity?", options: ["Galileo Galilei", "Isaac Newton", "Albert Einstein", "Johannes Kepler"], correctAnswer: "Isaac Newton", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the freezing point of water in Fahrenheit?", options: ["0°F", "32°F", "100°F", "212°F"], correctAnswer: "32°F", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Question Language", "System Quality Logic", "Standard Query List"], correctAnswer: "Structured Query Language", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the largest planet in our solar system by mass?", options: ["Saturn", "Jupiter", "Neptune", "Uranus"], correctAnswer: "Jupiter", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Who is known as the father of computers?", options: ["Alan Turing", "Charles Babbage", "Bill Gates", "Steve Jobs"], correctAnswer: "Charles Babbage", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the chemical symbol for silver?", options: ["Si", "Ag", "Au", "S"], correctAnswer: "Ag", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What does VPN stand for?", options: ["Virtual Private Network", "Visual Program Network", "Verified Personal Node", "Virtual Public Network"], correctAnswer: "Virtual Private Network", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], correctAnswer: "4", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the study of living organisms called?", options: ["Geology", "Biology", "Chemistry", "Physics"], correctAnswer: "Biology", category: "science", difficulty: "easy", points: 10, timeLimit: 15 },
    { question: "Who invented the first practical airplane?", options: ["Leonardo da Vinci", "Wright Brothers", "Henry Ford", "Charles Lindbergh"], correctAnswer: "Wright Brothers", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the chemical formula for carbon dioxide?", options: ["CO", "CO2", "C2O", "O2C"], correctAnswer: "CO2", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What does GPU stand for?", options: ["Graphics Processing Unit", "General Purpose Unit", "Global Processing Utility", "Graphical Program Unit"], correctAnswer: "Graphics Processing Unit", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the speed of light in vacuum (approximately)?", options: ["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s"], correctAnswer: "300,000 km/s", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "Who discovered radioactivity?", options: ["Marie Curie", "Henri Becquerel", "Ernest Rutherford", "Niels Bohr"], correctAnswer: "Henri Becquerel", category: "science", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "What is the chemical symbol for helium?", options: ["H", "He", "Hl", "Ho"], correctAnswer: "He", category: "science", difficulty: "easy", points: 10, timeLimit: 15 },
    { question: "What does API stand for in programming?", options: ["Application Programming Interface", "Automated Program Integration", "Advanced Protocol Interface", "Application Process Integration"], correctAnswer: "Application Programming Interface", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the normal human body temperature in Celsius?", options: ["35°C", "36°C", "37°C", "38°C"], correctAnswer: "37°C", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Who proposed the laws of motion?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Johannes Kepler"], correctAnswer: "Isaac Newton", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the chemical formula for ammonia?", options: ["NH3", "NH4", "N2H", "H3N"], correctAnswer: "NH3", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What does USB stand for?", options: ["Universal Serial Bus", "United System Board", "Universal System Bus", "United Serial Board"], correctAnswer: "Universal Serial Bus", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the largest bone in the human body?", options: ["Tibia", "Femur", "Humerus", "Fibula"], correctAnswer: "Femur", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Who invented the periodic table?", options: ["Marie Curie", "Dmitri Mendeleev", "Antoine Lavoisier", "John Dalton"], correctAnswer: "Dmitri Mendeleev", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the chemical symbol for mercury?", options: ["Me", "Hg", "Mr", "Mc"], correctAnswer: "Hg", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What does HTML stand for?", options: ["HyperText Markup Language", "High Transfer Markup Language", "HyperText Modern Language", "Home Tool Markup Language"], correctAnswer: "HyperText Markup Language", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the study of weather called?", options: ["Geology", "Meteorology", "Climatology", "Astronomy"], correctAnswer: "Meteorology", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Who discovered the electron?", options: ["Ernest Rutherford", "J.J. Thomson", "Niels Bohr", "James Chadwick"], correctAnswer: "J.J. Thomson", category: "science", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "What is the chemical formula for methane?", options: ["CH4", "C2H6", "CH3", "C2H4"], correctAnswer: "CH4", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What does CSS stand for in web development?", options: ["Cascading Style Sheets", "Computer Style System", "Creative Style Syntax", "Central Style Sheet"], correctAnswer: "Cascading Style Sheets", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "How many teeth does an adult human have?", options: ["28", "30", "32", "34"], correctAnswer: "32", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Who invented the steam engine?", options: ["Thomas Edison", "James Watt", "George Stephenson", "Robert Fulton"], correctAnswer: "James Watt", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the chemical symbol for copper?", options: ["Co", "Cu", "Cp", "C"], correctAnswer: "Cu", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What does OS stand for in computers?", options: ["Operating System", "Optical Storage", "Online Service", "Output System"], correctAnswer: "Operating System", category: "science", difficulty: "easy", points: 10, timeLimit: 15 },
    { question: "What is the study of stars and celestial objects called?", options: ["Astrology", "Astronomy", "Cosmology", "Astrophysics"], correctAnswer: "Astronomy", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Who discovered the neutron?", options: ["Ernest Rutherford", "James Chadwick", "Niels Bohr", "J.J. Thomson"], correctAnswer: "James Chadwick", category: "science", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "What is the chemical formula for glucose?", options: ["C6H12O6", "C12H22O11", "C6H6", "C2H5OH"], correctAnswer: "C6H12O6", category: "science", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "What does URL stand for?", options: ["Uniform Resource Locator", "Universal Resource Link", "Unified Reference Location", "Universal Resource Locator"], correctAnswer: "Uniform Resource Locator", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the main gas found in the air we breathe?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctAnswer: "Nitrogen", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "Who invented dynamite?", options: ["Alfred Nobel", "Thomas Edison", "Nikola Tesla", "Marie Curie"], correctAnswer: "Alfred Nobel", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the chemical symbol for lead?", options: ["L", "Ld", "Pb", "Le"], correctAnswer: "Pb", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What does PDF stand for?", options: ["Portable Document Format", "Personal Data File", "Print Document Format", "Public Display File"], correctAnswer: "Portable Document Format", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "What is the largest artery in the human body?", options: ["Pulmonary artery", "Aorta", "Carotid artery", "Femoral artery"], correctAnswer: "Aorta", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "Who invented the radio?", options: ["Thomas Edison", "Guglielmo Marconi", "Nikola Tesla", "Alexander Graham Bell"], correctAnswer: "Guglielmo Marconi", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the chemical formula for sulfuric acid?", options: ["H2SO4", "HCl", "HNO3", "H2CO3"], correctAnswer: "H2SO4", category: "science", difficulty: "hard", points: 20, timeLimit: 35 },
    { question: "What does Wi-Fi stand for?", options: ["Wireless Fidelity", "Wide Frequency", "Wireless Frequency", "Wide Fidelity"], correctAnswer: "Wireless Fidelity", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What is the smallest unit of life?", options: ["Atom", "Molecule", "Cell", "Organ"], correctAnswer: "Cell", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Who developed the polio vaccine?", options: ["Louis Pasteur", "Jonas Salk", "Alexander Fleming", "Edward Jenner"], correctAnswer: "Jonas Salk", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the chemical symbol for tin?", options: ["Ti", "Tn", "Sn", "T"], correctAnswer: "Sn", category: "science", difficulty: "hard", points: 20, timeLimit: 30 },
    { question: "What does SSD stand for in computers?", options: ["Solid State Drive", "Super Storage Device", "System State Disk", "Secure Storage Drive"], correctAnswer: "Solid State Drive", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What is the process by which plants make food?", options: ["Respiration", "Photosynthesis", "Digestion", "Fermentation"], correctAnswer: "Photosynthesis", category: "science", difficulty: "easy", points: 10, timeLimit: 20 },
    { question: "Who invented the printing press?", options: ["Johannes Gutenberg", "Benjamin Franklin", "William Caxton", "Aldus Manutius"], correctAnswer: "Johannes Gutenberg", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
    { question: "What is the chemical formula for hydrogen peroxide?", options: ["H2O", "H2O2", "HO2", "H3O"], correctAnswer: "H2O2", category: "science", difficulty: "medium", points: 15, timeLimit: 25 },
    { question: "What does HTTPS stand for?", options: ["HyperText Transfer Protocol Secure", "High Transfer Text Protocol System", "HyperText Transmission Process Secure", "Home Tool Transfer Protocol Secure"], correctAnswer: "HyperText Transfer Protocol Secure", category: "science", difficulty: "medium", points: 15, timeLimit: 30 },
];

// Read existing questions
import { questions as existingQuestions } from './seedData.js';

// Combine and export
const allQuestions = [...existingQuestions, ...additionalQuestions];

// Write to new file
const output = `export const questions = ${JSON.stringify(allQuestions, null, 4)};\n`;
fs.writeFileSync('./seedData_new.js', output);

console.log(`✅ Generated ${allQuestions.length} total questions`);
console.log(`   - Existing: ${existingQuestions.length}`);
console.log(`   - New: ${additionalQuestions.length}`);
